# Generated by Django 3.2.11 on 2022-12-07 11:44

from django.db import migrations, models
import django.utils.timezone
import utils.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to=utils.utility.PathAndRename('uploads/store')),
        ),
    ]
