# Generated by Django 3.2.11 on 2023-03-31 09:28

from django.db import migrations, models
import utils.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.ImageField(upload_to=utils.utility.PathAndRename('uploads/store')),
        ),
    ]
