# Generated by Django 3.2.11 on 2022-12-27 08:06

from django.db import migrations, models
import utils.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(default='noimage.png', upload_to=utils.utility.PathAndRename('uploads/store/qrcode')),
        ),
    ]
