# Generated by Django 3.2.11 on 2023-03-18 15:31

from django.db import migrations, models
import utils.utility


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(default='uploads/store/noimage.png', upload_to=utils.utility.PathAndRename('uploads/store/qrcode')),
        ),
    ]
