# Generated by Django 3.2.11 on 2022-11-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='username',
            new_name='telephone',
        ),
    ]
